name: <Native> Generate Emsdk Cache

on:
  workflow_dispatch:
    inputs:
      emsdk_version:
        description: 'Emsdk version'
        type: string
        default: '3.1.45'
        required: true

jobs:
  generate_emsdk_cache:
    name: "Generate Emsdk SDK cache"
    runs-on: ubuntu-latest
    steps:
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{ github.event.inputs.oh_sdk_version }}
          actions-cache-folder: 'emsdk-cache'

      - name: Verify
        run: emcc -v