name: <Native> Generate Emsdk Cache

on:
  workflow_dispatch:
    inputs:
      emsdk_version:
        description: 'Emsdk version'
        type: string
        default: '3.1.45'
        required: true

jobs:
  generate_emsdk_cache:
    name: "Generate Emsdk cache"
    runs-on: ubuntu-latest
    steps:
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@ab889da2abbcbb280f91ec4c215d3bb4f3a8f775
        with:
          version: ${{ github.event.inputs.emsdk_version }}
          actions-cache-folder: 'emsdk-cache'

      - name: Verify
        run: |
          which emcc
          emcc -v