name: <Native> Compile WebGPU

on:
  push:
    paths:
    - 'native/cocos/base/**'
    - 'native/cocos/renderer/gfx-base/**'
    - 'native/cocos/renderer/gfx-wgpu/**'
    - 'native/cocos/renderer/gfx-validator/**'
    - 'native/cocos/renderer/gfx-empty/**'
    - '.github/workflows/native-compile-webgpu.yml'

# github.head_ref is only defined on pull_request events
concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  compile_wgpu_mac:
    name: "Emscripten"
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.title, 'WGPU_CI_ON' )
    steps:
      - uses: actions/checkout@v2

      - name: Setup emsdk
        uses: dumganhar/setup-emsdk@997d2cde2deabda085a11f98e86e842915b0e846
        with:
          version: 3.1.45
          actions-cache-folder: 'emsdk-cache'

      - name: Verify
        run: |
          which emcc
          emcc -v

      - name: Compile
        env:
          COCOS_ENGINE_DEV: 1
        run: |
          NATIVE_ROOT=$GITHUB_WORKSPACE/native
          cd $NATIVE_ROOT/cocos/renderer/gfx-wgpu
          mkdir build
          cd build
          cmake .. -GNinja -DCMAKE_TOOLCHAIN_FILE=${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
          ninja
          echo "Compile WGPU by ems on Ubuntu Done!"
