name: <Native> Compile WebGPU

on:
  push:
    paths:
    - 'native/external-config.json'
    - 'native/cocos/base/**'
    - 'native/cocos/renderer/gfx-base/**'
    - 'native/cocos/renderer/gfx-wgpu/**'
    - 'native/cocos/renderer/gfx-validator/**'
    - 'native/cocos/renderer/gfx-empty/**'
    - '.github/workflows/native-compile-webgpu.yml'

# github.head_ref is only defined on pull_request events
concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  compile_wgpu_mac:
    name: "Emscripten"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download external libraries
        shell: bash
        run: |
          # EXT_VERSION=`node ./.github/workflows/get-native-external-version.js`
          EXT_VERSION="v3.8.2"
          git clone --branch $EXT_VERSION --depth 1 https://github.com/hana-alice/engine-native-external native/external

      - name: Setup emsdk
        uses: dumganhar/setup-emsdk@997d2cde2deabda085a11f98e86e842915b0e846
        with:
          version: 3.1.45
          actions-cache-folder: 'emsdk-cache'

      - name: Verify
        run: |
          which emcc
          emcc -v

      - name: Compile
        run: |
          NATIVE_ROOT=$GITHUB_WORKSPACE/native
          cd $NATIVE_ROOT/cocos/renderer/gfx-wgpu
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_BUILD_TYPE=Debug
          # ninja
          core_count=$(nproc)
          echo ">>>> core count: ${core_count}"
          make -j${core_count}
          echo "Compile WGPU by ems on Ubuntu Done!"
